
Swisscom:
  SimpleSamlServiceProvider:
    authSource: default-sp
    authTokenCookieName: SimpleSAMLAuthToken
    attributeKeys:
      username: 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'
    loginParams: {  }
    logoutParams: {  }
Neos:
  Flow:
    security:
      authentication:
        providers:
          SamlProvider:
            token: Swisscom\SimpleSamlServiceProvider\Security\Authentication\Token\SamlToken
            provider: Swisscom\SimpleSamlServiceProvider\Security\Authentication\Provider\SamlProvider
